'use client'

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactElement,
  type ReactNode,
} from 'react'

import { type DataSourceField } from '@docyrus/app-utils'
import { keepPreviousData, useMutation, useQuery } from '@tanstack/react-query'
import {
  type ColumnFiltersState,
  type ColumnSort,
  type PaginationState,
} from '@tanstack/react-table'
import {
  Download,
  Loader2,
  Pencil,
  RotateCw,
  Search,
  Trash2,
} from 'lucide-react'
import { type RuleGroupType } from 'react-querybuilder'

import {
  applyViewToTable,
  DataGridDisplayMenu,
  DataGridFilterMenu,
  DataGridGroupMenu,
  DataGridRowHeightMenu,
  DataGridSidePanel,
  DataGridSortMenu,
  getDataGridSelectColumn,
  useDataGrid,
  type ColumnDef,
  type DataGridAction,
  type RowChange,
  type SavedDataGridView,
} from '@/components/docyrus/data-grid'
import { toServerRule } from '@/components/docyrus/data-grid/lib/data-grid-server'
import { type CellUserOption } from '@/components/docyrus/data-grid/types'
import {
  type AsyncOptionsConfig,
  type ColumnConfig,
  type FilterStrategy,
} from '@/components/docyrus/data-table-filter/core/types'
import { type Locale as DataTableFilterLocale } from '@/components/docyrus/data-table-filter/lib/i18n'
import {
  DataTableSideFilters,
  useDataTableSideFilters,
  type SideFilterDefaults,
  type SideFilterSectionGroup,
  type DataTableSideFiltersProps,
} from '@/components/docyrus/data-table-side-filters'
import { DocyrusIcon } from '@/components/docyrus/docyrus-icon'
import {
  DataGridViewSelect,
  type DataGridViewSelectVariant,
} from '@/components/docyrus/data-grid-view-select'
import { BulkUpdateDialog } from '@/components/docyrus/bulk-update-dialog'
import { RecordDeleteConfirmDialog } from '@/components/docyrus/record-delete-confirm-dialog'

import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import { useDataExport, type DataExportColumn } from '@/hooks/use-data-export'
import {
  DocyrusDataExportMenu,
  encodeDocyrusDataExportColumn,
  type DocyrusDataExportFieldOption,
  type DocyrusDataExportSelection,
} from '@/components/docyrus/docyrus-data-export-menu'

import {
  useDocyrusDataExport,
  type DocyrusDataExportPayload,
} from './use-docyrus-data-export'
import { buildTanstackColumnDef } from './use-docyrus-field-component'
import {
  useDocyrusDataViewSelect,
  type UseDocyrusDataViewSelectOptions,
  type UseDocyrusDataViewSelectResult,
} from './use-docyrus-data-view-select'

/**
 * Shape of a TanStack DB collection generated by `@docyrus/tanstack-db-generator`.
 * Only `list` is required by this hook; consumers may pass the full collection.
 */
export interface DocyrusDataGridCollection<TData> {
  list: (
    params?: Record<string, unknown>,
  ) => Promise<Array<TData> | { data: Array<TData> }>
  /** PATCH `/items/bulk` — used for inline change save and bulk-update dialog. */
  updateMany?: (body: {
    records: Array<{ id: string } & Record<string, unknown>>
    enableAutomation?: boolean
    enableChangeLogging?: boolean
  }) => Promise<unknown>
  /** DELETE `/items` — used for bulk delete from the selection toolbar. */
  deleteMany?: (body: {
    recordIds: Array<string>
    childActions?: Record<string, 'keep' | 'delete' | 'user_decides'>
  }) => Promise<unknown>
}

/** Built-in bulk actions surfaced when one or more rows are selected. */
export type DocyrusDataGridBulkAction = 'update' | 'delete' | 'export'

/**
 * Field slugs the legacy Vue exporter dropped before forwarding the column
 * list to `query-export`. They're either internal bookkeeping (parent IDs,
 * sort_order, …) or duplicates of presentation metadata (`icon`, `color`).
 */
const DEFAULT_SERVER_EXPORT_EXCLUDED_SLUGS: ReadonlyArray<string> = [
  'data',
  'document',
  'parent_data_source_id',
  'parent_record_id',
  'icon',
  'color',
  'mentions',
  'followers',
  'type',
  'tenant_view_id',
  'tenant_data_source_id',
  'sort_order',
  'editor_view_id',
]

/**
 * Field types whose values aren't stored on the row and therefore don't
 * round-trip through the export pipeline (action buttons, etc.).
 */
const DEFAULT_SERVER_EXPORT_EXCLUDED_TYPES: ReadonlyArray<string> = [
  'field-action',
  'action',
]

/**
 * Shape of `ZodSelectQueryPayload` parameters passed to the items endpoint.
 * Mirrors the docs guide at `docs/guides/docyrus-api-query-guide.md`.
 */
export interface DocyrusDataGridListParams {
  columns?: string
  filters?: RuleGroupType | Record<string, unknown>
  filterKeyword?: string
  orderBy?:
    | string
    | { field: string; direction?: 'asc' | 'desc' }
    | Array<{ field: string; direction?: 'asc' | 'desc' }>
  limit?: number
  offset?: number
  fullCount?: boolean
  expand?: Array<string>
  expandTypes?: Array<'user' | 'enum' | 'relation'>
  [key: string]: unknown
}

/** Convenience alias to the parameter shape consumed by `useDataGrid`. */
type UseDataGridParams<TData> = Parameters<typeof useDataGrid<TData>>[0]

/**
 * Configuration for the optional side-panel filter rail rendered alongside
 * the grid. The hook wires the panel's emitted `RuleGroupType` into the
 * items request, ANDed with the saved view's `filterQuery` and any
 * toolbar filter rules.
 */
export interface DocyrusDataGridSideFiltersConfig<TData> {
  /**
   * Filter columns shown in the side panel. Mirrors the `columnsConfig`
   * accepted by `useDataTableFilters` / `useDataTableSideFilters`.
   */
  columnsConfig: ReadonlyArray<ColumnConfig<TData, any, any, any>>
  /**
   * Filter strategy passed to `useDataTableSideFilters`. Server-paged grids
   * should use `'server'` (the default) so values are surfaced as
   * `RuleGroupType` rules; `'client'` filters in-memory.
   */
  strategy?: FilterStrategy
  /** Per-column UI hints (collapsed / mode / threshold / hidden / sticky / etc.). */
  defaults?: SideFilterDefaults
  /** Optional grouping of filter sections into named blocks. */
  sections?: ReadonlyArray<SideFilterSectionGroup>
  /** Visual variant for the panel container. */
  variant?: DataTableSideFiltersProps<TData>['variant']
  /** Header title. Pass `null` to hide. Default `'Filters'`. */
  title?: DataTableSideFiltersProps<TData>['title']
  /** Show the active-filter chip strip below the header. Default `true`. */
  showActiveChips?: boolean
  /** Show "Clear all" button next to the title when any filter is active. Default `true`. */
  showClearAll?: boolean
  /**
   * When `true`, renders a search input above the sections. Pass a column id
   * to drive a specific text-typed column.
   */
  searchable?: boolean | string
  /** Override for the "Clear all" label. Default `'Clear all'`. */
  clearAllLabel?: string
  /** Override for the per-section "Clear" label. Default `'Clear'`. */
  clearLabel?: string
  /** Locale forwarded to the underlying filter UI. Default `'en'`. */
  locale?: DataTableFilterLocale
  /** Extra className for the panel root. */
  className?: string
  /** Override for the collapse-button accessible label. Default `'Collapse filters'`. */
  collapseAriaLabel?: string
  /** Override for the expand-button accessible label. Default `'Expand filters'`. */
  expandAriaLabel?: string
  /** Width of the collapsed rail (number → px). Default `36`. */
  collapsedWidth?: number | string
}

export interface UseDocyrusDataGridOptions<
  TData,
> extends UseDocyrusDataViewSelectOptions {
  /**
   * Pre-resolved rows. When provided, the hook skips its internal items query
   * — supply your own data, refetch, etc. Takes precedence over `collection`.
   */
  data?: Array<TData>
  /**
   * TanStack DB collection generated by `@docyrus/tanstack-db-generator`
   * (e.g., the result of `useBaseOrganizationCollection()`). The hook will
   * call `collection.list(listParams)` inside a `useQuery` to fetch rows.
   */
  collection?: DocyrusDataGridCollection<TData>
  /**
   * Extra query params merged on top of the params derived from the active
   * view (columns, filters, orderBy) and the toolbar search input
   * (filterKeyword). Use this for `expand`, `limit`/`offset`, `fullCount`, etc.
   */
  listParams?: DocyrusDataGridListParams
  /** Default page size when no `limit` is supplied via `listParams`. Default `100`. */
  defaultLimit?: number
  /**
   * Disable the internal items query. Useful when you want toolbar wiring
   * without fetching rows. Default `true` when no `data` is provided.
   */
  enableItemsQuery?: boolean
  /** Prepend a row-select checkbox column as the first column. Default `true`. */
  showSelectColumn?: boolean
  /** Show 1-based row markers on the select column when not selected. Default `true`. */
  enableRowMarkers?: boolean
  /** Override the default `getDataGridSelectColumn` definition entirely. */
  selectColumn?: ColumnDef<TData>
  /**
   * Optional actions column rendered as the **second** column (right after the
   * select column). Build it with `getDataGridActionsColumn({ cell: ... })`
   * and supply your own action buttons via `cell`.
   */
  actionsColumn?: ColumnDef<TData>
  /** Extra columns prepended after the select + actions columns. */
  extraColumns?: Array<ColumnDef<TData>>
  /** Per-field column override. Return `null` to skip a field entirely. */
  mapColumn?: (
    field: DataSourceField,
    defaultColumn: ColumnDef<TData>,
  ) => ColumnDef<TData> | null
  /** Forwarded to `useDataGrid`. */
  enableSearch?: boolean
  /** Forwarded to `useDataGrid`. Default `true` (required for the row-grouping picker to populate). */
  enableGrouping?: boolean
  /** Forwarded to `useDataGrid`. Default `true`. */
  readOnly?: boolean
  /** Toolbar feature toggles (all default to `true`). */
  enableViewSelect?: boolean
  /**
   * Variant for the view picker. Default `'horizontal-tabs'`. Use
   * `'dropdown'` for a compact toolbar (single Select-style trigger) or
   * `'vertical-tabs'` for sidebar layouts.
   */
  viewSelectVariant?: DataGridViewSelectVariant
  /**
   * Maximum number of view tabs to render inline in the
   * `'horizontal-tabs'` variant. Overflow tabs collapse into the active
   * view's overflow menu. Ignored for `'dropdown'` and `'vertical-tabs'`.
   */
  viewSelectMaxVisible?: number
  enableSearchInput?: boolean
  enableFilterMenu?: boolean
  enableGroupMenu?: boolean
  enableSortMenu?: boolean
  enableRowHeightMenu?: boolean
  enableDisplayMenu?: boolean
  enableReloadButton?: boolean
  /**
   * Show the server-side data export dropdown in the toolbar. Pulls all rows
   * matching the active view's filters/keyword from
   * `POST /v1/edge/run/query-export`. Default `true`.
   */
  enableServerExportMenu?: boolean
  /** Row cap forwarded to the server export endpoint. Default `10000`. */
  serverExportLimit?: number
  /**
   * Field types to skip when picking columns for the server export. Defaults
   * to virtual / non-stored types like `field-action`.
   */
  serverExportExcludedFieldTypes?: ReadonlyArray<string>
  /**
   * Field slugs to skip when picking columns for the server export. Defaults
   * to internal metadata columns mirroring the legacy Vue exporter.
   */
  serverExportExcludedSlugs?: ReadonlyArray<string>
  /**
   * Called when the toolbar reload button is clicked, after the items
   * query refetches. The toolbar button refetches records only — it does
   * not reload data source metadata or views. Use the returned `reload`
   * function (or `refetch`) when you need a full hard refresh.
   */
  onReload?: () => void
  /** Toolbar search input config. */
  searchPlaceholder?: string
  /** Debounce in ms before applying the search input. Default `300`. */
  searchDebounceMs?: number
  /** Extra className for the toolbar root. */
  toolbarClassName?: string
  /**
   * Custom node prepended to the left side of the built-in toolbar (next to
   * the view tabs and search input). Use for app-specific buttons or
   * filters that should sit alongside the standard controls.
   */
  toolbarStartContent?: ReactNode
  /**
   * Custom node appended to the right side of the built-in toolbar (after
   * the reload button). Use for app-specific actions like "Add record",
   * "Refresh metrics", etc.
   */
  toolbarEndContent?: ReactNode
  /**
   * Extra row-selection actions appended to the floating action bar after
   * the built-in `bulkActions` (`update`, `delete`, `export`). Each entry's
   * `onAction(selectedRows)` (or `render(selectedRows)`) receives the
   * currently selected rows so handlers can drive their own logic.
   */
  extraBulkActions?: Array<DataGridAction<TData>>
  /**
   * Track inline cell edits and surface a save/discard banner. Forwarded to
   * `useDataGrid` as `enableChangeTracking`. Default `true`.
   *
   * When enabled and the user clicks "Save", the hook batches every changed
   * row into a single `PATCH /items/bulk` call (`enableAutomation: false`,
   * `enableChangeLogging: false` per the bulk endpoint defaults). Override
   * via `onSaveChanges`.
   */
  trackChanges?: boolean
  /** Custom save-changes handler. Receives the changed rows + new full data array. */
  onSaveChanges?: (
    changes: Array<RowChange>,
    data: Array<TData>,
  ) => void | Promise<void>
  /**
   * Selection-bar bulk action toggles. Default: all three (`['update', 'delete', 'export']`).
   * Pass `false` (or an empty array) to hide the bar entirely.
   */
  bulkActions?: false | ReadonlyArray<DocyrusDataGridBulkAction>
  /**
   * Which fields to include when the user picks Export. `'visible'` (default) uses
   * the table's currently-visible columns; `'all'` includes every data-source field;
   * an explicit array picks specific slugs in order.
   */
  exportColumns?: 'visible' | 'all' | ReadonlyArray<string>
  /** File name (without extension) for exports. Default = `dataSourceSlug`. */
  exportFileName?: string
  /**
   * Tenant-wide users list to seed `field-userSelect` /
   * `field-userMultiSelect` cell options. When supplied, those cells render
   * avatars + labels using this list instead of the row's expanded payload
   * (which is still used as a fallback when a row references a user not in
   * the list). Typical usage: fetch `/v1/users` once at app boot and pass
   * the result here on every grid mount.
   */
  users?: ReadonlyArray<CellUserOption>
  /**
   * Tenant-aware date formatter used by `DateCell`. Pass
   * `dateUtils.formatDate` from `@docyrus/app-utils` so saved-view cells
   * render dates in the account's regional format.
   */
  formatDate?: (value: unknown) => string
  /**
   * Tenant-aware datetime formatter used by `DateTimeCell`. Pass
   * `dateUtils.formatDateTime` from `@docyrus/app-utils`.
   */
  formatDateTime?: (value: unknown) => string
  /**
   * Tenant-aware numeric formatter used by `NumberCell` /
   * `CurrencyCell` / `PercentCell`. Pass a function that wraps
   * `numberUtils.formatNumber` / `numberUtils.formatCurrency` /
   * `numberUtils.formatPercent` from `@docyrus/app-utils`.
   */
  formatNumber?: (
    value: unknown,
    opts?: { variant?: 'number' | 'currency' | 'percent'; currency?: string },
  ) => string
  /**
   * Conditional row color rules forwarded to `useDataGrid`. Each rule's
   * predicate runs against the row data and tints matching rows.
   */
  rowColorRules?: UseDataGridParams<TData>['rowColorRules']
  /**
   * Conditional cell color rules forwarded to `useDataGrid`. Targets
   * specific column ids and tints individual cells when their predicate
   * matches.
   */
  cellColorRules?: UseDataGridParams<TData>['cellColorRules']
  /**
   * Accessible label for a row, surfaced via `aria-label` on row elements
   * and used by the change-tracking save banner. Forwarded to `useDataGrid`.
   */
  getRowLabel?: UseDataGridParams<TData>['getRowLabel']
  /**
   * Inline "Add row" handler. When supplied, the grid renders the add-row
   * footer cell and Tab-out-of-last-cell shortcut. Forwarded to
   * `useDataGrid`. The handler may return a `CellPosition` to focus the
   * newly added cell.
   */
  onRowAdd?: UseDataGridParams<TData>['onRowAdd']
  /**
   * Initial TanStack Table state (sorting, columnFilters, rowSelection,
   * pagination, …). Forwarded to `useDataGrid`. Note that the active
   * saved view still drives the running state via `applyViewToTable`; use
   * this only for one-time defaults applied before any view is loaded.
   */
  initialState?: UseDataGridParams<TData>['initialState']
  /**
   * Activate the side-panel filter rail rendered alongside the grid. When
   * `true`, the hook's `sideFilters` return value renders a
   * `<DataTableSideFilters>` panel and feeds its emitted `RuleGroupType`
   * into the items request (ANDed with the saved view filter and any
   * toolbar filter menu rules). The toolbar filter menu remains available
   * — both can be used together. Default `false`.
   *
   * Requires `sideFiltersConfig` to be supplied with a `columnsConfig`.
   */
  enableSideFilters?: boolean
  /**
   * Required side-panel configuration when `enableSideFilters` is `true`.
   * Exposes the filter `columnsConfig`, optional section grouping, and
   * presentation overrides.
   */
  sideFiltersConfig?: DocyrusDataGridSideFiltersConfig<TData>
  /**
   * Initial expanded state for the side panel. When `false`, the panel
   * mounts collapsed and renders a vertical rail with a 90°-rotated
   * "Filters" label that re-expands the panel on click. Default `true`.
   */
  sideFiltersDefaultExpanded?: boolean
  /**
   * Controlled expanded state. Pair with `onSideFiltersExpandedChange`. When
   * omitted, the hook manages the state internally.
   */
  sideFiltersExpanded?: boolean
  /** Called when the user toggles the side-panel collapse/expand control. */
  onSideFiltersExpandedChange?: (expanded: boolean) => void
  /**
   * Width of the side panel when expanded. Number → px. Default `280`.
   * Applied via inline `style.width` on the wrapper.
   */
  sideFiltersWidth?: number | string
}

export interface UseDocyrusDataGridResult<TData> extends Omit<
  UseDocyrusDataViewSelectResult,
  'gridViewSelectProps'
> {
  /** TanStack Table instance — pass to `<DataGrid>` and any toolbar building blocks. */
  table: ReturnType<typeof useDataGrid<TData>>['table']
  /**
   * Spread onto `<DataGrid table={table} {...gridProps} />`. Includes the
   * bulk-action descriptors so the built-in floating selection bar lights up
   * automatically.
   */
  gridProps: Omit<ReturnType<typeof useDataGrid<TData>>, 'table'> & {
    actions?: Array<DataGridAction<TData>>
    /** True while a background refetch is in flight (e.g. toolbar reload). */
    isReloading?: boolean
  }
  /** Pre-wired toolbar element ready to render above the grid. */
  toolbar: ReactNode
  /**
   * Pre-wired side panel element. `null` for `'horizontal-tabs'` and
   * `'dropdown'` view variants. Returns a `<DataGridSidePanel>` containing
   * the vertical view picker when `viewSelectVariant === 'vertical-tabs'`.
   * Render to the left of `<DataGrid>` (e.g. inside a flex row) when
   * non-null.
   */
  sidePanel: ReactNode
  /**
   * Pre-wired side-panel filter element. `null` when `enableSideFilters`
   * is `false`. Renders the full panel when expanded and a thin vertical
   * rail (with a 90°-rotated "Filters" label) when collapsed. Render to
   * the left of `<DataGrid>` (typically inside the same flex row as
   * `sidePanel`).
   */
  sideFilters: ReactNode
  /** Current expanded state of the side filter panel. */
  sideFiltersExpanded: boolean
  /** Programmatically toggle the side filter panel expanded state. */
  setSideFiltersExpanded: (expanded: boolean) => void
  /**
   * Current `RuleGroupType` emitted by the side filter panel, or
   * `undefined` when no rules are active. Already merged into the items
   * request — exposed for inspection / persistence.
   */
  sideFiltersQuery: RuleGroupType | undefined
  /** Resolved rows passed to the grid — from `data`, `collection.list()`, or the direct items fetch. */
  items: Array<TData>
  /** The list params actually sent to the backend (after merging view state, search, and `listParams`). */
  resolvedListParams: DocyrusDataGridListParams
  /**
   * Resolved paging mode for the active view. Pass to `<DataGrid pagingMode>`
   * so the standard footer renders only when the view enables it.
   */
  pagingMode: 'standard' | 'virtual-scroll' | undefined
  /** Triggers `refetch()` (data source + views + items) and the optional `onReload` callback. */
  reload: () => void
}

export function useDocyrusDataGrid<TData>(
  options: UseDocyrusDataGridOptions<TData>,
): UseDocyrusDataGridResult<TData> {
  const {
    data: providedData,
    collection,
    listParams,
    defaultLimit = 100,
    enableItemsQuery = providedData === undefined,
    showSelectColumn = true,
    enableRowMarkers = true,
    selectColumn,
    actionsColumn,
    extraColumns,
    mapColumn,
    enableSearch = false,
    enableGrouping = true,
    readOnly = true,
    enableViewSelect = true,
    viewSelectVariant = 'horizontal-tabs',
    viewSelectMaxVisible,
    enableSearchInput = true,
    enableFilterMenu = true,
    enableGroupMenu = true,
    enableSortMenu = true,
    enableRowHeightMenu = true,
    enableDisplayMenu = true,
    enableReloadButton = true,
    enableServerExportMenu = true,
    serverExportLimit = 10000,
    serverExportExcludedFieldTypes,
    serverExportExcludedSlugs,
    onReload,
    searchPlaceholder = 'Search…',
    searchDebounceMs = 300,
    toolbarClassName,
    toolbarStartContent,
    toolbarEndContent,
    extraBulkActions,
    trackChanges = true,
    onSaveChanges,
    bulkActions = ['update', 'delete', 'export'],
    exportColumns = 'visible',
    exportFileName,
    users,
    formatDate,
    formatDateTime,
    formatNumber,
    rowColorRules,
    cellColorRules,
    getRowLabel,
    onRowAdd,
    initialState,
    enableSideFilters = false,
    sideFiltersConfig,
    sideFiltersDefaultExpanded = true,
    sideFiltersExpanded: sideFiltersExpandedProp,
    onSideFiltersExpandedChange,
    sideFiltersWidth = 280,
    ...viewSelectOptions
  } = options

  const bulkActionSet = useMemo(() => {
    if (bulkActions === false) return new Set<DocyrusDataGridBulkAction>()

    return new Set<DocyrusDataGridBulkAction>(bulkActions)
  }, [bulkActions])

  /*
   * Slot the items-query refetch into a ref so the bulk-action handlers
   * (declared higher in the hook than `itemsQuery`) can refresh the grid
   * after a successful mutation.
   */
  const itemsRefetchRef = useRef<(() => Promise<unknown>) | null>(null)

  /*
   * Stays in `viewSelectOptions` so it's forwarded to `useDocyrusDataViewSelect`,
   * but we also read it locally to seed the table grouping.
   */
  const { defaultRowGroupingColumn } = viewSelectOptions

  const viewSelect = useDocyrusDataViewSelect(viewSelectOptions)
  const {
    dataSource,
    gridViewSelectProps,
    refetch: refetchViewSelect,
    views,
    activeViewId,
  } = viewSelect

  const activeView = useMemo<SavedDataGridView | undefined>(
    () => views.find((view) => view.id === activeViewId),
    [views, activeViewId],
  )

  /*
   * Standard paging means the user explicitly opted into a paginated view.
   * Virtual-scroll (the default) keeps every loaded row in a single
   * virtualized viewport — no `limit/offset` round-trips, no manual
   * pagination on the table.
   */
  const isStandardPaging =
    activeView?.pagingEnabled === true &&
    (activeView.pagingMode ?? 'virtual-scroll') === 'standard'

  const initialPageSize = activeView?.pageSize ?? defaultLimit

  const [pagination, setPagination] = useState<PaginationState>(() => ({
    pageIndex: 0,
    pageSize: initialPageSize,
  }))

  const [searchInput, setSearchInput] = useState('')
  const [debouncedSearch, setDebouncedSearch] = useState('')
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([])

  /*
   * Re-sync pagination + clear toolbar filters when the upstream "key"
   * inputs change — store-and-compare pattern (per the React docs:
   * "You Might Not Need an Effect" → adjust state during render). This
   * avoids the `set-state-in-effect` lint and the extra render churn.
   *
   *   - active view change       → reset page + clear toolbar filters
   *     (different views can carry different `pageSize` settings, and
   *     transient relation filters from one view shouldn't leak into the
   *     next)
   *   - initialPageSize change   → reset page
   *   - search/columnFilters     → reset pageIndex (the underlying total
   *     shrinks, so a stale pageIndex could land out of bounds)
   */
  const [trackedActiveViewId, setTrackedActiveViewId] = useState(activeViewId)
  const [trackedInitialPageSize, setTrackedInitialPageSize] =
    useState(initialPageSize)
  const [trackedDebouncedSearch, setTrackedDebouncedSearch] =
    useState(debouncedSearch)
  const [trackedColumnFilters, setTrackedColumnFilters] =
    useState(columnFilters)

  if (trackedActiveViewId !== activeViewId) {
    setTrackedActiveViewId(activeViewId)
    setTrackedInitialPageSize(initialPageSize)
    setPagination({ pageIndex: 0, pageSize: initialPageSize })
    if (columnFilters.length > 0) setColumnFilters([])
  } else if (trackedInitialPageSize !== initialPageSize) {
    setTrackedInitialPageSize(initialPageSize)
    setPagination({ pageIndex: 0, pageSize: initialPageSize })
  } else if (
    trackedDebouncedSearch !== debouncedSearch ||
    trackedColumnFilters !== columnFilters
  ) {
    setTrackedDebouncedSearch(debouncedSearch)
    setTrackedColumnFilters(columnFilters)
    if (pagination.pageIndex !== 0) {
      setPagination((prev) => ({ ...prev, pageIndex: 0 }))
    }
  }

  useEffect(() => {
    const timeout = window.setTimeout(() => {
      setDebouncedSearch(searchInput)
    }, searchDebounceMs)

    return () => window.clearTimeout(timeout)
  }, [searchInput, searchDebounceMs])

  const groupingRequiredSlugs = useMemo<Array<string>>(() => {
    const fromView = activeView?.grouping ?? []

    if (fromView.length > 0) return fromView
    if (defaultRowGroupingColumn) return [defaultRowGroupingColumn]

    return []
  }, [activeView, defaultRowGroupingColumn])

  /*
   * Side-panel filter state. `useDataTableSideFilters` is a thin wrapper
   * around `useDataTableFilters` that emits a `RuleGroupType` whenever the
   * underlying `FiltersState` changes — we feed that rule group through
   * `buildFiltersParam` (alongside the saved view filter and toolbar
   * filter rules) so the items request stays in sync. The hook is always
   * called (Rules of Hooks), but with an empty `columnsConfig` when the
   * consumer hasn't enabled the side panel.
   */
  const sideFiltersColumnsConfig = useMemo(
    () =>
      sideFiltersConfig?.columnsConfig ??
      ([] as ReadonlyArray<ColumnConfig<TData, any, any, any>>),
    [sideFiltersConfig?.columnsConfig],
  )
  const sideFiltersStrategy: FilterStrategy =
    sideFiltersConfig?.strategy ?? 'server'
  const [sideFiltersQuery, setSideFiltersQuery] = useState<
    RuleGroupType | undefined
  >(undefined)
  const sideFilterDtf = useDataTableSideFilters<
    TData,
    ReadonlyArray<ColumnConfig<TData, any, any, any>>,
    FilterStrategy
  >({
    columnsConfig: sideFiltersColumnsConfig,
    strategy: sideFiltersStrategy,
    data: [],
    defaults: sideFiltersConfig?.defaults,
    sections: sideFiltersConfig?.sections,
    onQueryChange: setSideFiltersQuery,
  })
  const sideFiltersActiveQuery = enableSideFilters
    ? sideFiltersQuery
    : undefined

  const [internalSideFiltersExpanded, setInternalSideFiltersExpanded] =
    useState<boolean>(sideFiltersDefaultExpanded)
  const isSideFiltersControlled = sideFiltersExpandedProp !== undefined
  const sideFiltersExpanded = isSideFiltersControlled
    ? sideFiltersExpandedProp!
    : internalSideFiltersExpanded

  const setSideFiltersExpanded = useCallback(
    (next: boolean) => {
      if (!isSideFiltersControlled) setInternalSideFiltersExpanded(next)
      onSideFiltersExpandedChange?.(next)
    },
    [isSideFiltersControlled, onSideFiltersExpandedChange],
  )

  const resolvedListParams = useMemo<DocyrusDataGridListParams>(
    () =>
      buildListParams({
        fields: dataSource?.fields,
        view: activeView,
        filterKeyword: debouncedSearch.trim() || undefined,
        defaultLimit,
        override: listParams,
        requiredSlugs: groupingRequiredSlugs,
        pagination: isStandardPaging ? pagination : undefined,
        toolbarFilters: columnFilters,
        sideFilters: sideFiltersActiveQuery,
      }),
    [
      dataSource?.fields,
      activeView,
      debouncedSearch,
      defaultLimit,
      listParams,
      groupingRequiredSlugs,
      isStandardPaging,
      pagination,
      columnFilters,
      sideFiltersActiveQuery,
    ],
  )

  const itemsKey = useMemo(
    () =>
      [
        'docyrus',
        'docyrusDataGridItems',
        viewSelectOptions.appSlug,
        viewSelectOptions.dataSourceSlug,
        collection ? 'collection' : 'direct',
        resolvedListParams,
      ] as const,
    [
      viewSelectOptions.appSlug,
      viewSelectOptions.dataSourceSlug,
      collection,
      resolvedListParams,
    ],
  )

  /*
   * Gate the items query on the view metadata being fully ready so we don't
   * fire one request with all columns and a second with the active view's
   * whitelist. Specifically wait for:
   *  - the data source + views queries to settle (so `dataSource.fields` and
   *    `views` are populated, which feeds `resolvedListParams`),
   *  - if any views exist, an `activeViewId` to be picked (the resolution
   *    runs in a useEffect inside `useDocyrusDataViewSelect`).
   */
  const viewMetadataReady =
    !viewSelect.isLoading && (views.length === 0 || Boolean(activeViewId))

  const itemsQuery = useQuery<{
    items: Array<TData>
    total: number | undefined
  }>({
    queryKey: itemsKey,
    queryFn: async () => {
      const response = collection
        ? await collection.list(resolvedListParams)
        : await viewSelectOptions.client.get<
            Array<TData> | { data: Array<TData>; meta?: { total?: number } }
          >(
            `/v1/apps/${viewSelectOptions.appSlug}/data-sources/${viewSelectOptions.dataSourceSlug}/items`,
            resolvedListParams as Parameters<
              typeof viewSelectOptions.client.get
            >[1],
          )

      return {
        items: unwrapItems<TData>(response),
        total: unwrapTotal(response),
      }
    },
    enabled:
      providedData === undefined &&
      enableItemsQuery &&
      Boolean(viewSelectOptions.appSlug) &&
      Boolean(viewSelectOptions.dataSourceSlug) &&
      viewMetadataReady,
    staleTime: viewSelectOptions.staleTime ?? 30_000,
    /*
     * Keep the previous page's payload (including `meta.total`) on screen
     * while the next page is in flight. Without this, switching pages
     * blanks `data` for the new query key — `rowCount` reverts to
     * `undefined`, and TanStack's manual-pagination fallback computes
     * `getPageCount()` from `data.length` plus the current `pageIndex`,
     * yielding bogus values like "2 pages" until the new response lands.
     * `keepPreviousData` makes the transition smooth: total stays at
     * `meta.total`, page count stays at `ceil(total / pageSize)`, and
     * the visible rows swap when the fetch resolves.
     */
    placeholderData: keepPreviousData,
  })

  itemsRefetchRef.current = itemsQuery.refetch as () => Promise<unknown>

  /*
   * Resolved row set passed into TanStack. With standard paging on local
   * data we slice ourselves so `manualPagination` sees only the current
   * page (groups then form within the visible window — same trade-off as
   * server paging). With virtual-scroll mode or no paging, hand the rows
   * straight through.
   */
  const items = useMemo<Array<TData>>(() => {
    if (providedData) {
      if (isStandardPaging) {
        const start = pagination.pageIndex * pagination.pageSize

        return providedData.slice(start, start + pagination.pageSize)
      }

      return providedData
    }

    return itemsQuery.data?.items ?? []
  }, [
    providedData,
    itemsQuery.data,
    isStandardPaging,
    pagination.pageIndex,
    pagination.pageSize,
  ])

  /*
   * `rowCount` for the table:
   *  - Local + standard paging: full data length (we sliced for `items`).
   *  - Remote + standard paging: `meta.total` from the server (only
   *    populated when `fullCount: true` was sent — handled in
   *    `buildListParams`).
   *  - Virtual-scroll: leave undefined; TanStack falls back to data length.
   */
  const rowCount = useMemo<number | undefined>(() => {
    if (!isStandardPaging) return undefined
    if (providedData) return providedData.length

    return itemsQuery.data?.total
  }, [isStandardPaging, providedData, itemsQuery.data])

  const reload = useCallback(() => {
    refetchViewSelect()
    if (providedData === undefined) {
      void itemsQuery.refetch()
    }
    onReload?.()
  }, [refetchViewSelect, itemsQuery, providedData, onReload])

  /**
   * Toolbar reload — refetches records only. Keeps the data source
   * metadata + views queries intact so a routine refresh doesn't pay for
   * a full schema reload. Use `reload` when you need everything.
   */
  const reloadItems = useCallback(() => {
    if (providedData === undefined) {
      void itemsQuery.refetch()
    }
    onReload?.()
  }, [itemsQuery, providedData, onReload])

  /*
   * Forced read-only set: identity / autonumber columns and fields that
   * the data source itself flags as `readOnly: true`. These can NEVER be
   * toggled editable from the view editor — the editor's inline-editing
   * section reads `meta.forcedReadOnly` through `buildDraftColumns` and
   * renders the row as locked.
   */
  const forcedReadOnlySlugs = useMemo<Set<string>>(() => {
    const set = new Set<string>(['id', 'autonumber_id'])

    for (const field of dataSource?.fields ?? []) {
      const fieldRecord = field as Record<string, unknown>

      if (field.slug === 'id' || field.slug === 'autonumber_id') {
        set.add(field.slug)
      }

      if (fieldRecord.readOnly === true || fieldRecord.read_only === true) {
        set.add(field.slug)
      }

      const fieldType =
        typeof fieldRecord.type === 'string' ? fieldRecord.type : ''

      if (fieldType === 'field-autonumber' || fieldType === 'field-identity') {
        set.add(field.slug)
      }
    }

    return set
  }, [dataSource?.fields])

  /*
   * Combined "column is read-only at runtime" set: forced + the user's
   * per-view choice. The cell render path uses this; the editor reads
   * forced and user lists separately.
   */
  const effectiveReadOnlySlugs = useMemo<Set<string>>(() => {
    const set = new Set<string>(forcedReadOnlySlugs)

    for (const slug of activeView?.readOnlyColumns ?? []) {
      set.add(slug)
    }

    return set
  }, [forcedReadOnlySlugs, activeView?.readOnlyColumns])

  const columns = useMemo<Array<ColumnDef<TData>>>(() => {
    const fieldColumns = (dataSource?.fields ?? [])
      .map((field) => {
        const defaultColumn = buildTanstackColumnDef<TData>({
          field,
          appSlug: viewSelectOptions.appSlug,
          dataSourceSlug: viewSelectOptions.dataSourceSlug,
          users,
        })

        const mapped = mapColumn
          ? mapColumn(field, defaultColumn)
          : defaultColumn

        if (!mapped) return null

        /*
         * Stamp `meta.readOnly` (runtime: row uses this to gate editing)
         * and `meta.forcedReadOnly` (structural: editor uses this to
         * render the toggle as locked) AFTER `mapColumn` so caller
         * overrides can't accidentally drop the protection on identity /
         * metadata-locked fields. The merge preserves any other meta
         * properties the consumer set.
         */
        const isForced = forcedReadOnlySlugs.has(field.slug)
        const isReadOnly = effectiveReadOnlySlugs.has(field.slug)

        if (!isReadOnly && !isForced) return mapped

        return {
          ...mapped,
          meta: {
            ...mapped.meta,
            readOnly: isReadOnly,
            forcedReadOnly: isForced,
          },
        }
      })
      .filter((column): column is ColumnDef<TData> => column !== null)

    const resolvedSelectColumn = showSelectColumn
      ? (selectColumn ??
        getDataGridSelectColumn<TData>({
          size: 44,
          minSize: 44,
          enableRowMarkers,
        }))
      : null

    return [
      ...(resolvedSelectColumn ? [resolvedSelectColumn] : []),
      ...(actionsColumn ? [actionsColumn] : []),
      ...(extraColumns ?? []),
      ...fieldColumns,
    ]
  }, [
    dataSource?.fields,
    extraColumns,
    mapColumn,
    showSelectColumn,
    enableRowMarkers,
    selectColumn,
    actionsColumn,
    forcedReadOnlySlugs,
    effectiveReadOnlySlugs,
    viewSelectOptions.appSlug,
    viewSelectOptions.dataSourceSlug,
    users,
  ])

  const viewPagingMode = activeView?.pagingEnabled
    ? (activeView.pagingMode ?? 'virtual-scroll')
    : undefined

  /*
   * Default save-changes handler: collect every changed row's full snapshot
   * (post-edit) into a single bulk PATCH. Per the bulk endpoint docs, the
   * inline-edit path keeps automation + change-logging *off* to stay within
   * request budgets — re-enable explicitly via `onSaveChanges` if needed.
   */
  const defaultSaveChanges = useCallback(
    async (changes: Array<RowChange>, data: Array<TData>): Promise<void> => {
      if (changes.length === 0) return

      const changedIndexes = new Set(changes.map((change) => change.rowIndex))
      const records: Array<{ id: string } & Record<string, unknown>> = []

      for (const index of changedIndexes) {
        const row = data[index] as Record<string, unknown> | undefined
        const id = row?.id

        if (typeof id !== 'string' || id.length === 0) continue

        records.push({ ...row, id } as { id: string } & Record<string, unknown>)
      }

      if (records.length === 0) return

      const body = { records }

      if (collection?.updateMany) {
        await collection.updateMany(body)
      } else {
        await viewSelectOptions.client.patch(
          `/v1/apps/${viewSelectOptions.appSlug}/data-sources/${viewSelectOptions.dataSourceSlug}/items/bulk`,
          body,
        )
      }
    },
    [
      collection,
      viewSelectOptions.client,
      viewSelectOptions.appSlug,
      viewSelectOptions.dataSourceSlug,
    ],
  )

  const handleChangesSave = useCallback(
    async (changes: Array<RowChange>, data: Array<TData>): Promise<void> => {
      if (onSaveChanges) {
        await onSaveChanges(changes, data)
      } else {
        await defaultSaveChanges(changes, data)
      }

      if (providedData === undefined) {
        void itemsRefetchRef.current?.()
      }
    },
    [onSaveChanges, defaultSaveChanges, providedData],
  )

  /*
   * Inline-editing flips the table out of read-only mode when the active
   * view says so. It also force-enables change tracking — there's no
   * sensible way to surface in-flight edits to the user without a save /
   * discard banner, so we ignore a `trackChanges: false` override in this
   * mode (per the spec: "always use trackChanges when cell editing is
   * active").
   */
  const inlineEditingEnabled = activeView?.inlineEditingEnabled === true
  const effectiveReadOnly = readOnly && !inlineEditingEnabled
  const effectiveTrackChanges = inlineEditingEnabled ? true : trackChanges

  const { table, ...gridProps } = useDataGrid<TData>({
    data: items,
    columns,
    readOnly: effectiveReadOnly,
    enableSearch,
    enableGrouping,
    enableChangeTracking: effectiveTrackChanges,
    onChangesSave: handleChangesSave,
    pagingMode: viewPagingMode,
    pageSize: pagination.pageSize,
    rowColorRules,
    cellColorRules,
    getRowLabel,
    onRowAdd,
    initialState,
    /*
     * Standard paging → manual pagination. TanStack stops slicing client-
     * side (so group rows can't inflate the page count), our query drives
     * the data, and the footer reads `getRowCount()` / `getPageCount()`
     * from the values we feed below.
     */
    manualPagination: isStandardPaging,
    rowCount,
    manualFiltering: providedData === undefined,
    state: { pagination, columnFilters },
    onPaginationChange: setPagination,
    onColumnFiltersChange: setColumnFilters,
    meta: {
      ...(formatDate ? { formatDate } : {}),
      ...(formatDateTime ? { formatDateTime } : {}),
      ...(formatNumber ? { formatNumber } : {}),
      loadCellOptions: async (column, params) => {
        const config = getAsyncOptions(column)

        if (!config) return { items: [], hasMore: false }

        return config.load(params)
      },
    },
  })

  useEffect(() => {
    if (providedData === undefined) return
    table.setGlobalFilter(debouncedSearch || undefined)
  }, [debouncedSearch, providedData, table])

  /*
   * Apply the active view's full configuration (visibility, order, sort,
   * filters, color rules, paging, …) to the table whenever the active view
   * changes, including on initial mount AND when the same view's contents
   * change (e.g. the user saves new paging in the editor — the views query
   * refetches, `activeView` becomes a new object reference with the updated
   * fields, and we need to re-push the config to the table). The dep array
   * watches `activeView` directly so a same-id-but-different-content
   * refresh re-runs the effect.
   */
  useEffect(() => {
    if (!activeView) return
    if (!dataSource?.fields || dataSource.fields.length === 0) return

    applyViewToTable(table, activeView)

    const view = activeView

    /*
     * Force the active row-grouping column to stay visible even if the user
     * excluded it from the view — otherwise grouping silently breaks because
     * the column isn't part of the table's leaf columns rendered for the row.
     */
    const groupingForVisibility: Array<string> =
      (view.grouping ?? []).length > 0
        ? (view.grouping ?? [])
        : defaultRowGroupingColumn
          ? [defaultRowGroupingColumn]
          : []
    const enhancedVisibility = buildEnhancedVisibility(
      dataSource.fields,
      view,
      groupingForVisibility,
    )

    table.setColumnVisibility(enhancedVisibility)

    /*
     * Saved views store `columnOrder` with field slugs only (e.g.
     * `["name","email","phone","industry"]`). When TanStack applies a partial
     * order it appends unlisted columns at the end, so the row-select and
     * actions columns drift to the right. Re-pin them at the front.
     */
    const reservedIds: Array<string> = []

    if (showSelectColumn) reservedIds.push('select')
    if (actionsColumn) reservedIds.push('actions')

    if (reservedIds.length > 0) {
      const orderFromView = view.columnOrder ?? []

      table.setColumnOrder([
        ...reservedIds,
        ...orderFromView.filter((id) => !reservedIds.includes(id)),
      ])

      /*
       * Pin select + actions to the left so they stay visible during
       * horizontal scroll. Merge into whatever the saved view specified
       * (so a user's existing pinning preference is preserved) and dedupe.
       */
      const viewPinning = view.columnPinning ?? { left: [], right: [] }
      const left = [
        ...reservedIds,
        ...(viewPinning.left ?? []).filter((id) => !reservedIds.includes(id)),
      ]
      const right = (viewPinning.right ?? []).filter(
        (id) => !reservedIds.includes(id),
      )

      table.setColumnPinning({ left, right })
    }

    /*
     * If the saved view doesn't already specify a grouping but the consumer
     * passed `defaultRowGroupingColumn`, seed it as the initial grouping so
     * users land on a meaningful breakdown. Honors only fields that are
     * actually present in the data source.
     */
    const hasViewGrouping = (view.grouping ?? []).length > 0
    const fieldSlugs = new Set(dataSource.fields.map((field) => field.slug))

    if (
      !hasViewGrouping &&
      defaultRowGroupingColumn &&
      fieldSlugs.has(defaultRowGroupingColumn)
    ) {
      table.setGrouping([defaultRowGroupingColumn])
      table.setExpanded(true)
    }
  }, [
    activeView,
    dataSource?.fields,
    table,
    showSelectColumn,
    actionsColumn,
    defaultRowGroupingColumn,
  ])

  /*
   * `useDataGrid`'s `columnSizeVars` memo only depends on `[table, columnSizing]`,
   * so it doesn't recompute when the columns array changes. On initial mount
   * `dataSource.fields` is undefined and our columns are just `[select]`; once
   * fields load, new field columns are added but their `--col-*-size` CSS
   * variables are missing from the cached vars, leaving cells with invalid
   * `width: calc(undefined * 1px)`. Touching `columnSizing` forces the memo to
   * recompute against the now-complete header list. (Same trick the resize
   * handle uses, hence why a no-op resize click was "fixing" the layout.)
   */
  useEffect(() => {
    if (!dataSource?.fields || dataSource.fields.length === 0) return
    table.setColumnSizing((prev) => ({ ...prev }))
  }, [dataSource?.fields, table])

  /*
   * Lazy-load list of all data sources so relation filters can resolve a
   * `relationDataSourceId` (UUID) → `{ appSlug, slug }` (REST path). Fetched
   * on-demand the first time a filter menu touches a relation column and
   * cached for the session. Without this, filtering by a relation field
   * would have no way to query the related data source's items endpoint.
   */
  const dataSourcesLookupQuery = useQuery<
    Map<string, { appSlug: string; slug: string }>
  >({
    queryKey: ['docyrus', 'docyrusDataGridDataSources'],
    queryFn: async () => {
      const response = await viewSelectOptions.client.get<
        | { data?: Array<Record<string, unknown>> }
        | Array<Record<string, unknown>>
      >('/v1/apps/data-sources')
      const list = Array.isArray(response) ? response : (response?.data ?? [])
      const map = new Map<string, { appSlug: string; slug: string }>()

      for (const entry of list) {
        const id = typeof entry.id === 'string' ? entry.id : null
        const slug = typeof entry.slug === 'string' ? entry.slug : null
        const appSlugFromSnake =
          typeof entry.app_slug === 'string' ? entry.app_slug : null
        const appSlugFromCamel =
          typeof entry.appSlug === 'string' ? entry.appSlug : null
        const targetAppSlug = appSlugFromCamel ?? appSlugFromSnake

        if (id && slug && targetAppSlug) {
          map.set(id, { appSlug: targetAppSlug, slug })
        }
      }

      return map
    },
    enabled: false,
    staleTime: 5 * 60_000,
  })

  const ensureDataSourcesLookup = useCallback(async () => {
    if (dataSourcesLookupQuery.data) return dataSourcesLookupQuery.data
    const result = await dataSourcesLookupQuery.refetch()

    return result.data ?? new Map()
  }, [dataSourcesLookupQuery])

  const getAsyncOptions = useCallback(
    (column: {
      columnDef: { meta?: { cell?: unknown } }
    }): AsyncOptionsConfig | undefined => {
      const cellMeta = column.columnDef.meta?.cell as
        | {
            variant?: string
            dataSourceId?: string
            relationAppSlug?: string
            relationDataSourceSlug?: string
          }
        | undefined
      const variant = cellMeta?.variant

      if (variant === 'user' || variant === 'user-multi-select') {
        return {
          load: async ({ search, page, pageSize, signal }) => {
            const response = await viewSelectOptions.client.get<
              | {
                  data?: Array<Record<string, unknown>>
                  meta?: { total?: number }
                }
              | Array<Record<string, unknown>>
            >(
              '/v1/users',
              {
                filterKeyword: search || undefined,
                limit: pageSize,
                offset: page * pageSize,
                fullCount: true,
              } as Parameters<typeof viewSelectOptions.client.get>[1],
              { signal },
            )
            const items = Array.isArray(response)
              ? response
              : (response?.data ?? [])
            const total = !Array.isArray(response)
              ? response?.meta?.total
              : undefined
            const mapped = items
              .map((record) => {
                const id =
                  typeof record.id === 'string'
                    ? record.id
                    : typeof record.userId === 'string'
                      ? record.userId
                      : typeof record.user_id === 'string'
                        ? record.user_id
                        : null

                if (!id) return null

                const firstName =
                  typeof record.firstname === 'string'
                    ? record.firstname
                    : typeof record.firstName === 'string'
                      ? record.firstName
                      : typeof record.first_name === 'string'
                        ? record.first_name
                        : null
                const lastName =
                  typeof record.lastname === 'string'
                    ? record.lastname
                    : typeof record.lastName === 'string'
                      ? record.lastName
                      : typeof record.last_name === 'string'
                        ? record.last_name
                        : null
                const fullName = firstName
                  ? lastName
                    ? `${firstName} ${lastName}`
                    : firstName
                  : lastName
                const email =
                  typeof record.email === 'string' ? record.email : null
                const label = fullName ?? email ?? id
                const secondaryLabel =
                  email && email !== label ? email : undefined
                const imageUrl =
                  typeof record.photo === 'string'
                    ? record.photo
                    : typeof record.avatar_url === 'string'
                      ? record.avatar_url
                      : typeof record.avatarUrl === 'string'
                        ? record.avatarUrl
                        : typeof record.profile_image_url === 'string'
                          ? record.profile_image_url
                          : typeof record.profileImageUrl === 'string'
                            ? record.profileImageUrl
                            : undefined
                const icon = imageUrl ? undefined : (
                  <DocyrusIcon
                    icon="huge user-circle-02"
                    className="size-6 text-muted-foreground"
                  />
                )

                return {
                  value: id,
                  label,
                  ...(secondaryLabel ? { secondaryLabel } : {}),
                  ...(imageUrl ? { imageUrl } : {}),
                  ...(icon ? { icon } : {}),
                }
              })
              .filter(
                (
                  option,
                ): option is {
                  value: string
                  label: string
                  secondaryLabel?: string
                  imageUrl?: string
                  icon?: ReactElement
                } => option !== null,
              )
            const hasMore =
              typeof total === 'number'
                ? (page + 1) * pageSize < total
                : items.length === pageSize

            return { items: mapped, hasMore }
          },
        }
      }

      if (variant === 'relation') {
        const dataSourceId = cellMeta?.dataSourceId
        const directAppSlug = cellMeta?.relationAppSlug
        const directSlug = cellMeta?.relationDataSourceSlug

        if (!dataSourceId && !(directAppSlug && directSlug)) return undefined

        return {
          load: async ({ search, page, pageSize, signal }) => {
            /*
             * Prefer the slug+appSlug captured directly from the field
             * metadata (`relation_data_source_app_slug` /
             * `relation_data_source_slug`) so we don't have to fan out a
             * `/v1/apps/data-sources` lookup just to translate the UUID. The
             * lookup query stays as a fallback for legacy field metadata
             * that only carries the UUID.
             */
            let target: { appSlug: string; slug: string } | undefined =
              directAppSlug && directSlug
                ? { appSlug: directAppSlug, slug: directSlug }
                : undefined

            if (!target) {
              const lookup = await ensureDataSourcesLookup()

              if (signal?.aborted)
                throw new DOMException('Aborted', 'AbortError')

              target = dataSourceId ? lookup.get(dataSourceId) : undefined
            }

            if (!target) return { items: [], hasMore: false }

            const response = await viewSelectOptions.client.get<
              | {
                  data?: Array<Record<string, unknown>>
                  meta?: { total?: number }
                }
              | Array<Record<string, unknown>>
            >(
              `/v1/apps/${target.appSlug}/data-sources/${target.slug}/items`,
              {
                columns: 'id, name, autonumber_id',
                filterKeyword: search || undefined,
                limit: pageSize,
                offset: page * pageSize,
                fullCount: true,
              } as Parameters<typeof viewSelectOptions.client.get>[1],
              { signal },
            )
            const items = Array.isArray(response)
              ? response
              : (response?.data ?? [])
            const total = !Array.isArray(response)
              ? response?.meta?.total
              : undefined
            const mapped = items
              .map((record) => {
                const id = typeof record.id === 'string' ? record.id : null
                const label =
                  typeof record.name === 'string'
                    ? record.name
                    : typeof record.autonumber_id === 'string' ||
                        typeof record.autonumber_id === 'number'
                      ? String(record.autonumber_id)
                      : id

                if (!id || !label) return null

                return { value: id, label }
              })
              .filter(
                (option): option is { value: string; label: string } =>
                  option !== null,
              )
            const hasMore =
              typeof total === 'number'
                ? (page + 1) * pageSize < total
                : items.length === pageSize

            return { items: mapped, hasMore }
          },
        }
      }

      return undefined
    },
    [viewSelectOptions, ensureDataSourcesLookup],
  )

  /*
   * Server-side export wiring. The hook hands a query payload to
   * `POST /v1/edge/run/query-export` and lets the backend stream the result
   * as an xlsx attachment, so exports aren't bound by what's currently loaded
   * in the grid. Two scopes are surfaced through the toolbar menu:
   *
   *   - `'visible'` — columns the active view exposes (minus the internal
   *     metadata slugs and unexportable field types — same exclusions the
   *     legacy Vue exporter applied).
   *   - `'all'`     — every field flagged exportable on the data source,
   *     filtered by the same exclusions. Falls back to the entire field set
   *     when the data source lacks an explicit `export` flag.
   */
  const { exportData: exportServerData, isExporting: isServerExporting } =
    useDocyrusDataExport({
      client: viewSelectOptions.client,
      defaultLimit: serverExportLimit,
    })

  const serverExportableFields = useMemo<Array<DataSourceField>>(() => {
    const fields = dataSource?.fields ?? []

    if (fields.length === 0) return []

    const excludedSlugs = new Set<string>(
      serverExportExcludedSlugs ?? DEFAULT_SERVER_EXPORT_EXCLUDED_SLUGS,
    )
    const excludedTypes = new Set<string>(
      serverExportExcludedFieldTypes ?? DEFAULT_SERVER_EXPORT_EXCLUDED_TYPES,
    )

    return fields.filter((field) => {
      if (excludedSlugs.has(field.slug)) return false
      if (typeof field.type === 'string' && excludedTypes.has(field.type))
        return false

      const fieldRecord = field as Record<string, unknown>

      if (fieldRecord.export === false) return false

      return true
    })
  }, [
    dataSource?.fields,
    serverExportExcludedSlugs,
    serverExportExcludedFieldTypes,
  ])

  const serverExportColumnSlugs = useCallback(
    (scope: 'visible' | 'all'): Array<string> => {
      if (serverExportableFields.length === 0) return []

      if (scope === 'all') {
        return serverExportableFields.map((field) => field.slug)
      }

      const visibleSet = new Set(
        deriveVisibleSlugs(
          dataSource?.fields ?? [],
          activeView,
          groupingRequiredSlugs,
        ),
      )

      return serverExportableFields
        .filter((field) => visibleSet.has(field.slug))
        .map((field) => field.slug)
    },
    [
      serverExportableFields,
      dataSource?.fields,
      activeView,
      groupingRequiredSlugs,
    ],
  )

  const serverExportFieldOptions = useMemo<Array<DocyrusDataExportFieldOption>>(
    () =>
      serverExportableFields.map((field) => ({
        slug: field.slug,
        name:
          typeof field.name === 'string' && field.name.length > 0
            ? field.name
            : field.slug,
        type: typeof field.type === 'string' ? field.type : '',
      })),
    [serverExportableFields],
  )

  const serverExportVisibleSlugs = useMemo(
    () => serverExportColumnSlugs('visible'),
    [serverExportColumnSlugs],
  )

  const handleServerExport = useCallback(
    async (selection: DocyrusDataExportSelection) => {
      const dataSourceId =
        typeof dataSource?.id === 'string' ? dataSource.id : null

      if (!dataSourceId) return

      const columns =
        selection.scope === 'custom'
          ? selection.columns.map(encodeDocyrusDataExportColumn)
          : serverExportColumnSlugs(selection.scope)
      const payload: DocyrusDataExportPayload = {
        dataSourceId,
        columns: columns.length > 0 ? columns : '*',
        filters:
          resolvedListParams.filters as DocyrusDataExportPayload['filters'],
        filterKeyword:
          typeof resolvedListParams.filterKeyword === 'string'
            ? resolvedListParams.filterKeyword
            : undefined,
        limit: serverExportLimit,
      }

      await exportServerData(payload)
    },
    [
      dataSource?.id,
      serverExportColumnSlugs,
      resolvedListParams.filters,
      resolvedListParams.filterKeyword,
      serverExportLimit,
      exportServerData,
    ],
  )

  const canServerExport = enableServerExportMenu && Boolean(dataSource?.id)

  /*
   * Background refetch indicator. `isFetching` covers any in-flight request
   * including the toolbar reload button; we exclude `isLoading` so the
   * dedicated initial-mount skeleton/empty state isn't double-counted as a
   * reload. Drives the toolbar reload spinner + the grid body overlay.
   */
  const isReloading =
    providedData === undefined && itemsQuery.isFetching && !itemsQuery.isLoading

  /*
   * For `vertical-tabs`, the view picker lives in the side panel — keep it
   * out of the toolbar so the controls strip stays compact.
   */
  const renderViewSelectInToolbar =
    enableViewSelect && viewSelectVariant !== 'vertical-tabs'
  const renderViewSelectInSidePanel =
    enableViewSelect && viewSelectVariant === 'vertical-tabs'

  const controlsToolbar = useMemo<ReactNode>(
    () => (
      <div
        data-slot="docyrus-data-grid-toolbar"
        className={cn('flex flex-col gap-2 px-3 py-2', toolbarClassName)}
      >
        {(toolbarStartContent || renderViewSelectInToolbar) && (
          <div className="flex min-w-0 items-center gap-2 overflow-x-auto">
            {toolbarStartContent}
            {renderViewSelectInToolbar && (
              <DataGridViewSelect
                table={table}
                variant={viewSelectVariant}
                maxVisibleViews={viewSelectMaxVisible}
                editable
                {...gridViewSelectProps}
              />
            )}
          </div>
        )}
        <div className="flex items-start gap-2">
          <div className="flex min-w-0 flex-1 items-center gap-2 flex-wrap">
            {enableSearchInput && (
              <div className="relative shrink-0">
                <Search className="pointer-events-none absolute top-1/2 left-2 size-3.5 -translate-y-1/2 text-muted-foreground" />
                <Input
                  type="search"
                  value={searchInput}
                  onChange={(event) => setSearchInput(event.target.value)}
                  placeholder={searchPlaceholder}
                  className="h-8 w-56 pl-7"
                />
              </div>
            )}
            {enableFilterMenu && (
              <DataGridFilterMenu
                table={table}
                getAsyncOptions={getAsyncOptions}
                className="min-w-fit flex-1"
              />
            )}
          </div>
          <div className="flex flex-none shrink-0 items-center gap-2">
            {enableGroupMenu && (
              <DataGridGroupMenu
                table={table}
                defaultRowGroupingColumn={defaultRowGroupingColumn}
              />
            )}
            {enableSortMenu && <DataGridSortMenu table={table} />}
            {enableRowHeightMenu && <DataGridRowHeightMenu table={table} />}
            {enableDisplayMenu && <DataGridDisplayMenu table={table} />}
            {canServerExport && (
              <DocyrusDataExportMenu
                onExport={handleServerExport}
                fields={serverExportFieldOptions}
                visibleSlugs={serverExportVisibleSlugs}
                isExporting={isServerExporting}
              />
            )}
            {enableReloadButton && (
              <Button
                variant="outline"
                size="icon-sm"
                aria-label="Reload"
                disabled={isReloading}
                onClick={reloadItems}
              >
                {isReloading ? (
                  <Loader2 className="size-4 animate-spin" />
                ) : (
                  <RotateCw className="size-4" />
                )}
              </Button>
            )}
            {toolbarEndContent}
          </div>
        </div>
      </div>
    ),
    [
      table,
      gridViewSelectProps,
      searchInput,
      searchPlaceholder,
      toolbarClassName,
      toolbarStartContent,
      toolbarEndContent,
      renderViewSelectInToolbar,
      viewSelectVariant,
      viewSelectMaxVisible,
      enableSearchInput,
      enableFilterMenu,
      enableGroupMenu,
      enableSortMenu,
      enableRowHeightMenu,
      enableDisplayMenu,
      enableReloadButton,
      reloadItems,
      defaultRowGroupingColumn,
      getAsyncOptions,
      canServerExport,
      handleServerExport,
      serverExportFieldOptions,
      serverExportVisibleSlugs,
      isServerExporting,
      isReloading,
    ],
  )

  /*
   * Bulk-action wiring. The actual floating bar is rendered by `<DataGrid>`
   * via its built-in `actions` prop; this hook just produces the action
   * descriptors plus the dialogs they trigger.
   */
  const [bulkUpdateOpen, setBulkUpdateOpen] = useState(false)
  const [bulkDeleteOpen, setBulkDeleteOpen] = useState(false)
  const [isBulkDeleting, setIsBulkDeleting] = useState(false)
  const [bulkUpdateRecords, setBulkUpdateRecords] = useState<
    ReadonlyArray<TData>
  >([])
  const [bulkDeleteIds, setBulkDeleteIds] = useState<ReadonlyArray<string>>([])
  const [bulkDeleteCount, setBulkDeleteCount] = useState(0)

  const exportColumnDefs = useMemo<Array<DataExportColumn<TData>>>(() => {
    const fields = dataSource?.fields ?? []
    const visibility = table.getState().columnVisibility

    const slugs = (() => {
      if (Array.isArray(exportColumns)) return exportColumns
      if (exportColumns === 'all') return fields.map((field) => field.slug)

      return fields
        .map((field) => field.slug)
        .filter((slug) => visibility[slug] !== false)
    })()

    return slugs
      .map((slug) => fields.find((field) => field.slug === slug))
      .filter((field): field is DataSourceField => field !== undefined)
      .map<DataExportColumn<TData>>((field) => ({
        id: field.slug,
        header:
          typeof field.name === 'string' && field.name.length > 0
            ? field.name
            : field.slug,
      }))
  }, [dataSource?.fields, exportColumns, table])

  const { exportData } = useDataExport<TData>({
    columns: exportColumnDefs,
    fileName: exportFileName ?? viewSelectOptions.dataSourceSlug ?? 'export',
  })

  const clearSelection = useCallback(() => {
    table.toggleAllRowsSelected(false)
  }, [table])

  const bulkDeleteMutation = useMutation({
    mutationFn: async (recordIds: ReadonlyArray<string>) => {
      const body = { recordIds: [...recordIds] }

      if (collection?.deleteMany) {
        await collection.deleteMany(body)

        return
      }

      await viewSelectOptions.client.delete(
        `/v1/apps/${viewSelectOptions.appSlug}/data-sources/${viewSelectOptions.dataSourceSlug}/items`,
        body,
      )
    },
  })

  const onConfirmBulkDelete = useCallback(async () => {
    if (bulkDeleteIds.length === 0) return

    setIsBulkDeleting(true)

    try {
      await bulkDeleteMutation.mutateAsync(bulkDeleteIds)
      setBulkDeleteOpen(false)
      clearSelection()

      if (providedData === undefined) {
        void itemsRefetchRef.current?.()
      }
    } finally {
      setIsBulkDeleting(false)
    }
  }, [bulkDeleteIds, bulkDeleteMutation, clearSelection, providedData])

  const onBulkUpdateSuccess = useCallback(() => {
    clearSelection()

    if (providedData === undefined) {
      void itemsRefetchRef.current?.()
    }
  }, [clearSelection, providedData])

  const bulkActionDescriptors = useMemo<Array<DataGridAction<TData>>>(() => {
    if (
      bulkActionSet.size === 0 &&
      (!extraBulkActions || extraBulkActions.length === 0)
    )
      return []

    const list: Array<DataGridAction<TData>> = []

    if (bulkActionSet.has('update')) {
      list.push({
        key: 'bulk-update',
        label: 'Update',
        icon: <Pencil className="size-4" />,
        onAction: (rows) => {
          if (rows.length === 0) return
          setBulkUpdateRecords(rows)
          setBulkUpdateOpen(true)
        },
      })
    }

    if (bulkActionSet.has('delete')) {
      list.push({
        key: 'bulk-delete',
        label: 'Delete',
        icon: <Trash2 className="size-4" />,
        variant: 'destructive',
        onAction: (rows) => {
          const ids = rows
            .map((row) => (row as { id?: unknown }).id)
            .filter(
              (id): id is string => typeof id === 'string' && id.length > 0,
            )

          if (ids.length === 0) return

          setBulkDeleteIds(ids)
          setBulkDeleteCount(rows.length)
          setBulkDeleteOpen(true)
        },
      })
    }

    if (bulkActionSet.has('export')) {
      list.push({
        key: 'bulk-export',
        label: 'Export',
        render: (rows) => (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="secondary" size="sm">
                <Download className="size-4" />
                Export
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => void exportData(rows, 'csv')}>
                CSV
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => void exportData(rows, 'xlsx')}>
                Excel (.xlsx)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => void exportData(rows, 'json')}>
                JSON
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => void exportData(rows, 'markdown')}
              >
                Markdown
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        ),
      })
    }

    if (extraBulkActions && extraBulkActions.length > 0) {
      list.push(...extraBulkActions)
    }

    return list
  }, [bulkActionSet, exportData, extraBulkActions])

  const bulkDialogs =
    bulkActionSet.size > 0 ? (
      <>
        {bulkActionSet.has('update') && (
          <BulkUpdateDialog
            open={bulkUpdateOpen}
            onOpenChange={(next) => {
              setBulkUpdateOpen(next)
              if (!next) setBulkUpdateRecords([])
            }}
            client={viewSelectOptions.client}
            appSlug={viewSelectOptions.appSlug}
            dataSourceSlug={viewSelectOptions.dataSourceSlug}
            records={bulkUpdateRecords as ReadonlyArray<{ id: string }>}
            onSuccess={onBulkUpdateSuccess}
          />
        )}
        {bulkActionSet.has('delete') && (
          <RecordDeleteConfirmDialog
            open={bulkDeleteOpen}
            onOpenChange={(next) => {
              if (!next && !isBulkDeleting) {
                setBulkDeleteOpen(false)
                setBulkDeleteIds([])
                setBulkDeleteCount(0)
              }
            }}
            recordCount={bulkDeleteCount}
            isPending={isBulkDeleting}
            onConfirm={onConfirmBulkDelete}
          />
        )}
      </>
    ) : null

  const toolbar = (
    <>
      {controlsToolbar}
      {bulkDialogs}
    </>
  )

  const sidePanel: ReactNode = renderViewSelectInSidePanel ? (
    <DataGridSidePanel>
      <DataGridViewSelect
        table={table}
        variant="vertical-tabs"
        editable
        {...gridViewSelectProps}
      />
    </DataGridSidePanel>
  ) : null

  const expandedSideFilterWidth =
    typeof sideFiltersWidth === 'number'
      ? `${sideFiltersWidth}px`
      : sideFiltersWidth
  const sideFiltersNode: ReactNode =
    enableSideFilters && sideFiltersConfig ? (
      <DataTableSideFilters
        columns={sideFilterDtf.columns}
        filters={sideFilterDtf.filters}
        actions={sideFilterDtf.actions}
        strategy={sideFilterDtf.strategy}
        defaults={sideFilterDtf.defaults}
        sections={sideFilterDtf.sections}
        locale={sideFiltersConfig.locale}
        variant={sideFiltersConfig.variant}
        title={sideFiltersConfig.title}
        showActiveChips={sideFiltersConfig.showActiveChips}
        showClearAll={sideFiltersConfig.showClearAll}
        searchable={sideFiltersConfig.searchable}
        clearAllLabel={sideFiltersConfig.clearAllLabel}
        clearLabel={sideFiltersConfig.clearLabel}
        className={cn(
          'h-full shrink-0 overflow-y-auto border-r p-3',
          sideFiltersConfig.className,
        )}
        style={
          sideFiltersExpanded ? { width: expandedSideFilterWidth } : undefined
        }
        collapsible
        expanded={sideFiltersExpanded}
        onExpandedChange={setSideFiltersExpanded}
        collapsedWidth={sideFiltersConfig.collapsedWidth}
        collapseAriaLabel={sideFiltersConfig.collapseAriaLabel}
        expandAriaLabel={sideFiltersConfig.expandAriaLabel}
      />
    ) : null

  /*
   * Inject the bulk-action descriptors into the grid props the consumer
   * spreads onto `<DataGrid>` — that's the floating action bar already
   * implemented by `data-grid.tsx`. `actions` is a `<DataGrid>` prop (not
   * part of `useDataGrid`'s output), so we just attach it.
   */
  const gridPropsWithActions = useMemo<
    UseDocyrusDataGridResult<TData>['gridProps']
  >(
    () => ({
      ...gridProps,
      ...(bulkActionDescriptors.length > 0
        ? { actions: bulkActionDescriptors }
        : {}),
      isReloading,
    }),
    [gridProps, bulkActionDescriptors, isReloading],
  )

  const isLoading =
    viewSelect.isLoading ||
    (providedData === undefined && (itemsQuery.isLoading || !viewMetadataReady))
  const error = viewSelect.error ?? (itemsQuery.error as Error | null) ?? null

  const pagingMode: 'standard' | 'virtual-scroll' | undefined =
    activeView?.pagingEnabled
      ? (activeView.pagingMode ?? 'virtual-scroll')
      : undefined

  return {
    table,
    gridProps: gridPropsWithActions,
    toolbar,
    sidePanel,
    sideFilters: sideFiltersNode,
    sideFiltersExpanded,
    setSideFiltersExpanded,
    sideFiltersQuery: sideFiltersActiveQuery,
    items,
    resolvedListParams,
    pagingMode,
    reload,
    views: viewSelect.views,
    fields: viewSelect.fields,
    dataSource: viewSelect.dataSource,
    activeViewId: viewSelect.activeViewId,
    setActiveViewId: viewSelect.setActiveViewId,
    isLoading,
    error,
    refetch: reload,
  }
}

function unwrapItems<TData>(
  value: Array<TData> | { data: Array<TData> } | unknown,
): Array<TData> {
  if (Array.isArray(value)) return value
  if (
    value &&
    typeof value === 'object' &&
    Array.isArray((value as { data?: unknown }).data)
  ) {
    return (value as { data: Array<TData> }).data
  }

  return []
}

/**
 * Pull `meta.total` out of a response when present. The Docyrus API only
 * populates this when the request asks for `fullCount: true` — we send
 * that automatically whenever standard paging is active so the grid can
 * compute total pages without having to load every row.
 */
function unwrapTotal(value: unknown): number | undefined {
  if (!value || typeof value !== 'object') return undefined

  const { meta } = value as { meta?: unknown }

  if (!meta || typeof meta !== 'object') return undefined

  const { total } = meta as { total?: unknown }

  return typeof total === 'number' ? total : undefined
}

/*
 * ---------------------------------------------------------------------------
 * List params derivation — turns active view + search + overrides into the
 * `ZodSelectQueryPayload` shape consumed by the Docyrus data-source items
 * endpoint. See `docs/guides/docyrus-api-query-guide.md`.
 * ---------------------------------------------------------------------------
 */

interface BuildListParamsArgs {
  fields: Array<DataSourceField> | undefined
  view: SavedDataGridView | undefined
  filterKeyword?: string
  defaultLimit: number
  override: DocyrusDataGridListParams | undefined
  /**
   * Slugs that must be present in the resolved column list regardless of the
   * view's visibility/order. Used to ensure the active row-grouping column
   * is always fetched even if the user excluded it from the view.
   */
  requiredSlugs?: Array<string>
  /**
   * Active pagination state — when supplied, switches the request into
   * server-paged mode: `limit` / `offset` are derived from this and
   * `fullCount: true` is added so the response carries `meta.total`.
   * Undefined means "no remote paging" (virtual-scroll mode); the legacy
   * behavior of seeding `limit: defaultLimit, offset: 0` still applies.
   */
  pagination?: { pageIndex: number; pageSize: number }
  /**
   * Toolbar filter state from the DataTableFilter menu. ANDed onto the
   * saved view's `filterQuery` so server-paged grids refetch when the user
   * adds a transient filter from the toolbar.
   */
  toolbarFilters?: ColumnFiltersState
  /**
   * Optional `RuleGroupType` emitted by the side-panel filter rail. ANDed
   * onto the saved view filter alongside `toolbarFilters`.
   */
  sideFilters?: RuleGroupType | undefined
}

function buildListParams(args: BuildListParamsArgs): DocyrusDataGridListParams {
  const {
    fields,
    view,
    filterKeyword,
    defaultLimit,
    override,
    requiredSlugs,
    pagination,
    toolbarFilters,
    sideFilters,
  } = args

  const params: DocyrusDataGridListParams = {}

  const visibleSlugs = fields
    ? deriveVisibleSlugs(fields, view, requiredSlugs)
    : []
  const columns = buildColumnsParam(fields, view, requiredSlugs)

  if (columns) params.columns = columns

  const orderBy = buildOrderByParam(view?.sorting)

  if (orderBy) params.orderBy = orderBy

  const filters = buildFiltersParam(
    view?.filterQuery,
    toolbarFilters,
    sideFilters,
  )

  if (filters) params.filters = filters

  if (filterKeyword) params.filterKeyword = filterKeyword

  const expand = buildExpandParam(fields, visibleSlugs)

  if (expand && expand.length > 0) params.expand = expand

  params.limit = defaultLimit
  params.offset = 0

  if (override) Object.assign(params, override)

  /*
   * Pagination state wins over both `defaultLimit` and caller-supplied
   * `override.limit/offset` — once the user is on page N of a paginated
   * view, that's the source of truth for what the request should fetch.
   * `fullCount: true` instructs the API to populate `meta.total` so the
   * grid footer can show "X of N" and compute the page count without
   * having to load every record.
   */
  if (pagination) {
    params.limit = pagination.pageSize
    params.offset = pagination.pageIndex * pagination.pageSize
    params.fullCount = true
  }

  return params
}

function buildColumnsParam(
  fields: Array<DataSourceField> | undefined,
  view: SavedDataGridView | undefined,
  requiredSlugs: Array<string> | undefined,
): string | undefined {
  if (!fields || fields.length === 0) return undefined

  const visibleSlugs = deriveVisibleSlugs(fields, view, requiredSlugs)

  if (visibleSlugs.length === 0) return undefined

  return ['id', ...visibleSlugs.filter((slug) => slug !== 'id')].join(', ')
}

/**
 * Field types whose stored value is an ID reference — fetching the related
 * record (user, enum option, related row, …) requires explicitly expanding
 * the field. Any field of one of these types whose slug is visible in the
 * current request is added to `expand` so the API resolves the reference.
 */
const EXPANDABLE_FIELD_TYPES = new Set<string>([
  'field-userSelect',
  'field-userMultiSelect',
  'field-relation',
  'field-relatedField',
  'field-select',
  'field-radioGroup',
  'field-enum',
  'field-systemEnum',
  'field-multiSelect',
  'field-tagSelect',
  'field-status',
  'field-approvalStatus',
])

function buildExpandParam(
  fields: Array<DataSourceField> | undefined,
  visibleSlugs: Array<string>,
): Array<string> | undefined {
  if (!fields || fields.length === 0 || visibleSlugs.length === 0)
    return undefined

  const visible = new Set(visibleSlugs)

  return fields
    .filter(
      (field) =>
        visible.has(field.slug) && EXPANDABLE_FIELD_TYPES.has(field.type),
    )
    .map((field) => field.slug)
}

/**
 * Resolve the active view into the ordered list of field slugs that should be
 * fetched + rendered. Honors the explicit whitelist semantics used by saved
 * views: when `columnOrder` is non-empty, it acts as the whitelist (in order);
 * otherwise the visibility map's `true` entries are the whitelist. With no
 * explicit config, all fields are visible.
 *
 * `requiredSlugs` are appended (deduped) so the active row-grouping column
 * is always part of the resolved list — otherwise grouping by a column that
 * the user excluded from the view would silently fail.
 */
function deriveVisibleSlugs(
  fields: Array<DataSourceField>,
  view: SavedDataGridView | undefined,
  requiredSlugs?: Array<string>,
): Array<string> {
  const allSlugs = fields.map((field) => field.slug)
  const fieldSlugSet = new Set(allSlugs)
  const required = (requiredSlugs ?? []).filter((slug) =>
    fieldSlugSet.has(slug),
  )

  let visible: Array<string>

  if (!view) {
    visible = allSlugs
  } else {
    const visibility = view.columnVisibility ?? {}
    const order = view.columnOrder ?? []

    if (order.length > 0) {
      visible = order.filter(
        (slug) => fieldSlugSet.has(slug) && visibility[slug] !== false,
      )
    } else if (Object.keys(visibility).length > 0) {
      visible = allSlugs.filter((slug) => visibility[slug] === true)
    } else {
      visible = allSlugs
    }
  }

  if (required.length === 0) return visible

  const seen = new Set(visible)
  const result = [...visible]

  for (const slug of required) {
    if (!seen.has(slug)) {
      seen.add(slug)
      result.push(slug)
    }
  }

  return result
}

function buildEnhancedVisibility(
  fields: Array<DataSourceField>,
  view: SavedDataGridView,
  requiredSlugs?: Array<string>,
): Record<string, boolean> {
  const visibleSet = new Set(deriveVisibleSlugs(fields, view, requiredSlugs))
  const map: Record<string, boolean> = {}

  for (const field of fields) {
    map[field.slug] = visibleSet.has(field.slug)
  }

  return map
}

function buildOrderByParam(
  sorting: Array<ColumnSort> | undefined,
): Array<{ field: string; direction: 'asc' | 'desc' }> | undefined {
  if (!sorting || sorting.length === 0) return undefined

  return sorting.map((sort) => ({
    field: sort.id,
    direction: sort.desc ? 'desc' : 'asc',
  }))
}

function buildFiltersParam(
  filterQuery: SavedDataGridView['filterQuery'],
  toolbarFilters?: ColumnFiltersState,
  sideFilters?: RuleGroupType | undefined,
): RuleGroupType | undefined {
  const viewFilter =
    filterQuery &&
    'rules' in filterQuery &&
    Array.isArray(filterQuery.rules) &&
    filterQuery.rules.length > 0
      ? (filterQuery as RuleGroupType)
      : undefined

  const toolbarRules = (toolbarFilters ?? [])
    .map((filter) => toServerRule(filter))
    .filter(
      (rule): rule is { field: string; operator: string; value?: unknown } =>
        Boolean(rule),
    )

  const sideRule =
    sideFilters &&
    Array.isArray(sideFilters.rules) &&
    sideFilters.rules.length > 0
      ? sideFilters
      : undefined

  const groupCount = (viewFilter ? 1 : 0) + (sideRule ? 1 : 0)

  if (groupCount === 0 && toolbarRules.length === 0) return undefined
  if (groupCount === 1 && toolbarRules.length === 0) {
    return (viewFilter ?? sideRule) as RuleGroupType
  }
  if (groupCount === 0) {
    return { combinator: 'and', rules: toolbarRules } as RuleGroupType
  }

  const rules: Array<
    RuleGroupType | { field: string; operator: string; value?: unknown }
  > = []

  if (viewFilter) rules.push(viewFilter)
  if (sideRule) rules.push(sideRule)
  for (const r of toolbarRules) rules.push(r)

  return { combinator: 'and', rules } as RuleGroupType
}
