// Generated collection for base/message
import { apiClient } from '../lib/api'
import type { QueryParamValue } from '@docyrus/api-client'
import type { ICollectionListParams } from './types'

export interface BaseMessageEntity {
  /** ID */
  id?: string

  /** Record owner */
  record_owner?: string

  /** Created On */
  created_on?: string

  /** Created By */
  created_by?: string

  /** Last Modified On */
  last_modified_on?: string

  /** Last Modified By */
  last_modified_by?: string

  /** Subject */
  subject: string

  /** AI Connection ID */
  tenant_ai_connection_id?: { id: string; name: string } | string

  /** Draft */
  draft?: boolean

  /** Message Type */
  message_type?: { id: string; name: string } | any

  /** Thread */
  thread?: { id: string; name: string } | string

  /** Body Text */
  body_text?: string

  /** Body */
  body?: string

  /** View ID */
  tenant_view_id?: { id: string; name: string } | string

  /** AI Agent Deployment ID */
  tenant_ai_agent_deployment_id?: { id: string; name: string } | string

  /** Archived */
  archived?: boolean

  /** Regenerated By Message ID */
  regenerated_by_message_id?: { id: string; name: string } | string

  /** Body Json */
  body_json?: Record<string, any>

  /** Sent At */
  sent_at?: string

  /** Agent ID */
  tenant_assistant_id?: { id: string; name: string } | string

  /** Direction */
  direction?: { id: string; name: string } | any

  /** External Message ID */
  message_id?: string

  /** Sender Phone */
  sender_phone?: string

  /** Sender Name */
  sender_name?: string

  /** Files */
  files?: Record<string, any>

  /** Sender E-Mail */
  sender_email?: string

  /** Message Source */
  message_source?: { id: string; name: string } | any

  /** Sender CC */
  sender_cc?: string

  /** Sender BCC */
  sender_bcc?: string

  /** Send To Email */
  send_to_email?: string

  /** AI Model ID */
  core_ai_model_id?: { id: string; name: string } | string
}

export const baseMessageCollection = {
  /** List records with optional filtering, sorting, and pagination. */
  list: (params?: ICollectionListParams): Promise<Array<BaseMessageEntity>> =>
    apiClient.get(
      '/v1/apps/base/data-sources/message/items',
      params as Record<string, QueryParamValue> | undefined,
    ),

  /** Get record */
  get: (
    recordId: string,
    params?: { columns?: Array<string> },
  ): Promise<BaseMessageEntity> =>
    apiClient.get(
      '/v1/apps/base/data-sources/message/items/{recordId}'.replace(
        '{recordId}',
        recordId,
      ),
      params,
    ),

  /** Create record */
  create: (data: { data: any }): Promise<BaseMessageEntity> =>
    apiClient.post('/v1/apps/base/data-sources/message/items', data),

  /** Update record */
  update: (recordId: string, data: { data: any }): Promise<BaseMessageEntity> =>
    apiClient.patch(
      '/v1/apps/base/data-sources/message/items/{recordId}'.replace(
        '{recordId}',
        recordId,
      ),
      data,
    ),

  /** Delete record */
  delete: (recordId: string): Promise<void> =>
    apiClient.delete(
      '/v1/apps/base/data-sources/message/items/{recordId}'.replace(
        '{recordId}',
        recordId,
      ),
    ),

  /** Delete many records */
  deleteMany: (data: { recordIds: Array<string> }): Promise<void> =>
    apiClient.delete('/v1/apps/base/data-sources/message/items', data),
}
